### ISSUE TITLE
Zmiana formularza logowania

### ISSUE THREAD

**Issue by szjakub** [szjakub/cyprus#33]
@sylwek2531 @patrykszla 
zmienił się formularz rejestracji szkoły, zerknijcie na endpoint `/api/schools/` w ` /api/docs/ ` z brancha `develop`
teraz będą wymagane

user:
- email
- first_name
- last_name

school:
- school_name
- school_address

niestety musiałem to przerobić, bo mamy trochę rozbudowaną logikę zarządzania userami

**Comment by sylwek2531** [comment]
Tka jak gadalismy zwrtora z obiektem użytkownika

**Comment by szjakub** [comment]
@sylwek2531  dodałem rolę przy requeście o token, przykład na /api/docs/
